#+BEGIN_COMMENT
.. title: 那些提高效率的Alfred Workflow
.. slug: na-xie-ti-gao-xiao-lu-de-alfred-workflow
.. date: 2018-09-21 10:02:49 UTC+08:00
.. tags: alfred
.. category: tools
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* Alfred Browser Toolbox
  :PROPERTIES:
  :ID:       06FACFD5-9C4A-4549-8EED-7AEC3D77B480
  :END:
  Toolbox是一个文件操作浏览的工具，它支持创建、查找文件的功能，还可以查询pdf文件，非常方便。Mac上的Finder使用确定不方便。[[https://www.alfredforum.com/topic/5166-copymove-to-and-alfred-browser-workflows/][这里]]有具体的使用方式。
* Alfred Keywords Help
  :PROPERTIES:
  :ID:       49717B74-5702-483B-9E17-33D57893ED79
  :END:
   安装的workflow多了，记忆触发的keyword就比较困难，使用[[https://github.com/pochemuto/alfred-help-workflow][Keywords help]]这个插件可以显示出所有已经安装的workflow的触发key，还可以根据workflow进行查询。
* Alfred Maestro
  :PROPERTIES:
  :ID:       784CA9EA-34BE-415E-B5F8-5122EE866885
  :END:
   操作Maestro的workflow，可以直接查找macro并执行。[[https://github.com/iansinnott/alfred-maestro][插件地址]]
* Alfred My Mind
  :PROPERTIES:
  :ID:       A7DE7E80-197F-45B4-9C21-71CBB239224F
  :END:
  快速查询[[https://nikitavoloboev.xyz/][Nikita]]的githubpage内容的workflow，我在他的文章里面学到了很多。[[https://github.com/nikitavoloboev/alfred-my-mind#readme][插件地址]]
* Awesome lists
  :PROPERTIES:
  :ID:       35B0B749-2CE5-4E3B-BF74-E19299CEB25C
  :END:
  快速查询Github上awesome列表的workflow，只为发现更多。[[https://github.com/nikitavoloboev/alfred-awesome-lists][插件地址]]，这个也是Nikita的作品。
* Baidu Map
  :PROPERTIES:
  :ID:       8927BBDF-C1D1-46D2-B787-BED1476D08AB
  :END:
   在alfred上使用百度地图。[[https://github.com/wofeiwo/alfred-baidu-map][插件地址]]
* Birthday
  :PROPERTIES:
  :ID:       56143948-8358-4530-84DA-666BBA6B3F89
  :END:
   在alfred中显示你来到这个世界多长时间，让你珍惜每一分，每一秒。[[https://github.com/nikitavoloboev/small-workflows/tree/master/birthday#readme][插件地址]]
* Calendar
  :PROPERTIES:
  :ID:       0249D0F7-6AEC-4B4D-98DA-F5BBFA612BE6
  :END:
   在alfred中显示出当月的日历信息。[[https://github.com/owenwater/alfred-cal][插件地址]]
* Chromes Bookmarks
  :PROPERTIES:
  :ID:       BE3C62A7-8564-4B7B-97E1-464DC5ADD771
  :END:
   在aflred中搜索Chrome浏览器的书签，非常的好用。[[https://github.com/blainesch/alfred-chrome-bookmarks][插件地址]]
* Common Search
  :PROPERTIES:
  :ID:       7A5576D5-6ECD-496B-B29D-3AB3632F6D3A
  :END:
   国内常用网站的搜索，现在支持知乎、淘宝、掘金、github。[[https://github.com/MuYunyun/commonSearch][插件地址]]
* Dash
  :PROPERTIES:
  :ID:       582CC0AD-7614-4FAA-8CD3-0DE84B380A50
  :END:
   在alfred中进行Dash的搜索，开发者必备。[[https://github.com/Kapeli/Dash-Alfred-Workflow][插件地址]]
* Directory watches
  :PROPERTIES:
  :ID:       A11F5899-DB1E-4A8A-A65D-201AAA4A85A5
  :END:
   本地目录文件查看，指定目录的搜索，回收站文件显示。
* Emacs Workflow
  :PROPERTIES:
  :ID:       1D4EB2D4-0D51-442C-B754-0DD326A2A8DE
  :END:
   在alfred中进行emacs的操作，比如打开文件等。[[https://www.alfredforum.com/topic/8444-emacs-workflow/][插件地址]]
* Eudic
  :PROPERTIES:
  :ID:       CEDC7309-2013-47E4-A24F-44F174E45288
  :END:
** 插件说明
   :PROPERTIES:
   :ID:       BB1E1F7B-C8D8-4F95-93E4-97F03AB48241
   :END:
   使用欧路词典进行快速翻译。[[https://github.com/cdpath/eudic_tools][插件地址]]
* Git Repos
  :PROPERTIES:
  :ID:       024A5F17-021A-4080-9A19-922F35F7CA2C
  :END:
** 插件说明
   :PROPERTIES:
   :ID:       70B62A05-407D-438E-BA65-EDCA996CFFE8
   :END:
   搜索本地的git文件夹，搜索到后可以使用指定软件进行打开，开发时很有用。[[https://github.com/deanishe/alfred-repos][插件地址]]
** 插件说明
   :PROPERTIES:
   :ID:       23BB0C6B-8928-419E-8D7F-1ED5F8EFFFA5
   :END:
   搜索github上的项目，可以搜索项目，人物等。[[https://github.com/gharlan/alfred-github-workflow][插件地址]]
* Google Chrome History
  :PROPERTIES:
  :ID:       81A1FCE3-1AE3-4DD8-847C-2B48289BE260
  :END:
   在alfred中快速查看Chrome的浏览历史。[[https://github.com/tupton/alfred-chrome-history][插件地址]]
* Hammerspoon Workflow
  :PROPERTIES:
  :ID:       7BE62DC1-ADB6-4F06-B5F6-4C3C81882B08
  :END:
  在alfred中调用hammerspon脚本的workflow。[[https://www.alfredforum.com/topic/5334-hammerspoon-workflow/][插件地址]]
* Homebrew & Cask for Alfred
  :PROPERTIES:
  :ID:       8DC01423-3721-4D91-8F6D-8FC3C67115CC
  :END:
   在alfred中进行mac软件的更新、查看、安装等。[[https://github.com/fniephaus/alfred-homebrew/][插件地址]]
* iTerm Sessions
  :PROPERTIES:
  :ID:       10218152-446D-42E4-8D4E-CF3E7BA598F1
  :END:
   在alfre中快速切换iterm中存在的session窗口。[[https://github.com/madvas/alfred-iterm-sessions][插件地址]]
* Kill Process
  :PROPERTIES:
  :ID:       3426706F-953B-4464-869B-BFEB68EFBBA9
  :END:
   在alfred中kill进程，有时候程序假死，使用这个很方便，不用再在苹果的菜单栏中点击好几下来操作了。[[https://github.com/nathangreenstein/alfred-process-killer][插件地址]]
* Last changed files
  :PROPERTIES:
  :ID:       FE3BF159-26CC-4D02-95DC-E8AC3393B8C7
  :END:
   显示出当前系统最新修改的文件，对于系统有什么修改一目了然。
* Launcher
  :PROPERTIES:
  :ID:       F7872C53-3F87-4A9E-A90D-E2701D343046
  :END:
   应用程序快速启动workflow，结束Karabiner使用。
* Learn Anything
  :PROPERTIES:
  :ID:       433CC6A2-1555-4C17-98AD-27353548F7C0
  :END:
   Nivita的Learn Anything，只为学习更多。[[https://github.com/nikitavoloboev/alfred-learn-anything][插件地址]]
* Linux Command
  :PROPERTIES:
  :ID:       60006CDE-E02A-4828-92E8-2ECDED8268CB
  :END:
   Linux命令手册，快速查询linux命令。[[https://github.com/jaywcjlove/linux-command][插件地址]]
* Mail.app Search
  :PROPERTIES:
  :ID:       929CF82B-8B2C-4C05-8E14-6EC004B29319
  :END:
   快速搜索Mail.app中的邮件信息。可以根据邮件名，发送人，主题等进行搜索。[[http://www.packal.org/workflow/mailapp-search][插件地址]]
* MyIP
  :PROPERTIES:
  :ID:       C0D62E25-FF33-49C1-82B0-1AD25978BA52
  :END:
   快速的查询本机的ip，包括本地IP与外网IP。
* MenuBar Search
  :PROPERTIES:
  :ID:       0408FFD2-A2AE-4F49-9A0D-84EE0E5856F3
  :END:
  快速查询当前应用的菜单信息，点击进行操作。
* NSC
  :PROPERTIES:
  :ID:       DA90B235-A56A-4360-94E9-00C1647DC319
  :END:
   各种进制的转换，支持二进制、十进制、十六进制之间的快速转换。[[https://github.com/obstschale/NSC][插件地址]]
* org-mode-capture
  :PROPERTIES:
  :ID:       9209A35D-3D61-45A9-B8BD-25538F35B8E2
  :END:
   快速插入Org capture，可以快速的记录TODO事件。[[https://github.com/alexandergogl/alfred-org-mode-workflow][插件地址]]
* Packal Search
  :PROPERTIES:
  :ID:       9E445427-E5CD-449B-BA91-61DFBEF26466
  :END:
   Alfred workflow的快速搜索、更新。[[https://github.com/deanishe/alfred-packal-search][插件地址]]
* Recent Documents / Apps
  :PROPERTIES:
  :ID:       36ECE447-1661-4B7A-93A3-2DA900A803D8
  :END:
   显示当前的文档信息，当前的app信息，当前app关联的文档信息。[[https://github.com/mpco/Alfred3-workflow-recent-documents][插件地址]]
* Search Safari and Chrome Tabs
  :PROPERTIES:
  :ID:       A41488FA-B6F7-4ED7-B749-C221D0DEFA77
  :END:
    搜索Chrome和Safari当前打开的tab页面，支持跳转到选择页面。[[http://www.packal.org/workflow/search-safari-and-chrome-tabs][插件地址]]
* Searchio!
  :PROPERTIES:
  :ID:       496F6122-8863-4020-8C14-1E0DACC18462
  :END:
   支持google、youtuebe、wiki的fuzzy搜索，支持配置多种语言。[[https://github.com/deanishe/alfred-searchio][插件地址]]
* SSH SecureCRT
  :PROPERTIES:
  :ID:       9A0BF988-2311-47D8-8CC6-48DCA22BD735
  :END:
   在alfre快速连接SecureCRT的session。
* StackOverflow
  :PROPERTIES:
  :ID:       B50A0847-AACE-48BB-BB84-1B728A8FD3D8
  :END:
   搜索stackoverflow上的指定问题。[[https://github.com/deanishe/alfred-stackoverflow][插件地址(deanishe)]] 
* Swift Window Switcher
  :PROPERTIES:
  :ID:       8F1A51E6-77C2-488A-875E-D4933DF92B11
  :END:
   使用alfred来快速切换应用的窗口，还可以对safari的当前标签进行搜索。[[https://github.com/mandrigin/AlfredSwitchWindows][插件地址]]
* SwitchHosts!
  :PROPERTIES:
  :ID:       5F9D7E27-626F-4AA4-9BD5-F6D6699F7E3D
  :END:
   在alfred中快速本地host的配置，配合[[https://github.com/oldj/SwitchHosts][SwitchHosts]]来使用。[[http://www.packal.org/workflow/switchhosts][插件地址]]
* SnippetsLab
  :PROPERTIES:
  :ID:       1D102922-78C3-4CE5-9B2E-D6597475F93E
  :END:
  在alfred中快速查看SnippetsLab中的代码片断
* Tldr
  :PROPERTIES:
  :ID:       1DDA64C3-16EA-4CAC-93F7-9F94F3CD7DE8
  :END:
   Tldr的alfred版本，快速查询命令。[[https://github.com/cs1707/tldr-alfred][插件地址]]
* Uninstall with CleanMyMac X
  :PROPERTIES:
  :ID:       24331980-1F67-4F56-B2BC-611B5AD361AD
  :END:
   使用CleanMyMac来快速卸载软件。[[http://www.packal.org/workflow/uninstall-cleanmymac-x][插件地址]]
* VagrantUP
  :PROPERTIES:
  :ID:       4717273F-3FD0-41E2-8129-B54E49F59613
  :END:
    控制vagrant的workflow，可以显示vagrant的环境，根据name，path进行过滤等。[[https://github.com/m1keil/alfred-vagrant-workflow][插件地址]]
* VMWare Control
  :PROPERTIES:
  :ID:       E0A0B020-F936-44C5-B060-44FEE22DE9F5
  :END:
   在alfred中控制vmware虚拟机。支持启动、停止、挂起、切换等操作。[[http://www.packal.org/workflow/vmware-control][插件地址]]
* Web Searches
  :PROPERTIES:
  :ID:       23FA43C2-A45D-491D-9EC6-CF7E3A719F4F
  :END:
   通用的web搜索，支持reddit，google translate等网站搜索。[[https://github.com/nikitavoloboev/alfred-web-searches][插件地址]]
* WeChat Plugin
  :PROPERTIES:
  :ID:       22EA63EA-EBCA-49D8-9880-41B39AC40AB6
  :END:
   在alfred中进行微信聊天，可以显示聊天记录，超级方便。[[https://github.com/TKkk-iOSer/WeChatPlugin-MacOS][插件地址]]
* Wi-Fi
  :PROPERTIES:
  :ID:       72D51B8A-7C70-4E0D-9F7E-359464014DA2
  :END:
   控制Mac的ip开关，新更新的版本增加了重启wifi的功能。[[https://github.com/ravelll/wifi-workflow][插件地址]]
* Youdao Translate
  :PROPERTIES:
  :ID:       95EFB24B-5451-46BD-B668-7F76501EA079
  :END:
   有道词典快速查询翻译，支持中英互译，发音，记录查询历史等功能。[[https://github.com/Rouwanzi/AlfredWorkflow_YoudaoTranslate][插件地址]]
* Zapier for Alfred
  :PROPERTIES:
  :ID:       B66C2574-28E1-4B82-90D2-0BAAC9879BCD
  :END:
   在alfred中触发zapier流，目前还在尝试中。[[https://github.com/zapier/Zapier-for-Alfred/][插件地址]]
